### ISSUE TITLE
Provide ability to leverage custom domains in SSL CN

### ISSUE THREAD

**Issue by ody** [timidri/terraform-aws-pe_arch#11]
## Use Case

Users often have organization specific domain names that they should be able to utilize as a component of the common name for the SSL certificates which represent infrastructure nodes that are part of their Puppet Enterprise deployments on AWS

## Describe the Solution You Would Like

When this Terraform module is ran to provision PE infrastructure a variable should be passed which is the custom domain to associated with new instances, that combination of the Terraform generated instance name and custom domain should be concatenated and stored as an instance tag to allow for us to query the value from other tools.

This module should not handle the creation of hosted zones or adding entries to it.

## Describe Alternatives You've Considered

Embed zone and entry creation into the module but DNS implementation varies between organizations and introduce additional unnecessary complexity into the Terraform code. This is probably better handled via a user supplied module and orchestration through Bolt. 

## Additional Context

This should be ported to other providers and is similar to the solution we use for making internal DNS a property of the GCP instances we deploy in [GCP](https://github.com/puppetlabs/terraform-google-pe_arch/blob/main/modules/instances/main.tf#L54), request from user that this feature is derived from was working on AWS

**Comment by davidsandilands** [comment]
The parts of this ticket which are valid were completed in https://github.com/puppetlabs/terraform-aws-pe_arch/pull/24 but the SSL part is not valid
