### ISSUE TITLE
Allow existing VPC

### ISSUE THREAD

**Issue by cdenneen** [timidri/terraform-aws-pe_arch#16]
## Use Case
Build out PE stacks using existing VPC resources (vpc, subnets, routing, gateway)

## Describe the Solution You Would Like
Allow to specify existing vpc id to use for resources that require it when not creating a new vpc.

The networking module should still create/manage security groups needed per stack but not manage any existing "networking" resources previously setup outside of this scope.

**Comment by timidri** [comment]
@cdenneen Thanks, this is already on our roadmap to implement!

**Comment by ody** [comment]
This was added with the merging of pull request https://github.com/puppetlabs/terraform-aws-pe_arch/pull/19
